apiVersion: v1
kind: Pod
metadata:
  name: app-secret
spec:
  containers:
    - name: app-secret
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
      resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret